[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
remappings = [
  "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/",
]

[rpc_endpoints]
unichain_sepolia = "${UNICHAIN_SEPOLIA_RPC}"
